name: Master-Build
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}   
        fetch-depth: 0    

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.17'
    - name: Test
      run: make test-all

    - name: Git Version
      id: tag_version
      uses: codacy/git-version@2.2.0
      with:
        prefix: v

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      with:
        tag_name: ${{ steps.tag_version.outputs.version }}
        release_name: Release ${{ steps.tag_version.outputs.version }}
