name: Master-Build
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.5
    - name: Linting
      uses: "actions-contrib/golangci-lint@master"
      args: "run"
    - name: Test
      run: go test ./...
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
