name: Release
on: [ workflow_dispatch ]
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.17'
    - name: goreleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
